version: '2.0.0.{build}'
environment:
  CODECOV_TOKEN:
    secure: 3cc8d6a1-6ea2-4aa3-98e8-3d19ae46adc8
image: Visual Studio 2017
skip_branch_with_pr: true
skip_commits:
  files:
  - '**/*.md'

before_build:
- choco install opencover.portable
- choco install codecov

build:
  verbosity: normal

build_script:
  - dotnet build misc/vs/Gcode.sln -c Release
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test tools/TestSuite/Gcode.Test/Gcode.Test.csproj" -filter:"+[Gcode]* -[Gcode.Test]*" -output:".\coverage.xml"
  - codecov -f coverage.xml -t 3cc8d6a1-6ea2-4aa3-98e8-3d19ae46adc8

artifacts:
  - path: 'src\Gcode.Utils\bin\Release\*.nupkg'
    name: NuGet Package (Release)

  - path: coverage.xml
    name: Coverage Report

deploy:
  provider: NuGet
  api_key:
    secure: aqkB1JtbMkc7X/GvoNX5zmX5TUQSsUQ/4L8fUujUJducDenNK8axwRvl89g5oJY3
  skip_symbols: true
  artifact: /.*\.nupkg/